# Generated by Django 4.1.10 on 2023-10-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='busCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='media')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='Catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.buscatagory'),
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
