# Generated by Django 4.1.10 on 2023-10-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_buscatagory_alter_bus_catagory_delete_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscatagory',
            name='Image',
            field=models.ImageField(upload_to='bus_images'),
        ),
    ]
